# Generated by Django 5.1.15 on 2026-03-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='simulation.simulation'),
        ),
    ]
