# Generated by Django 5.1.15 on 2026-03-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy_level', models.CharField(default='base', help_text='simplified, base, full', max_length=20)),
                ('global_wealth', models.FloatField(default=1000.0)),
                ('stability_index', models.FloatField(default=0.7, help_text='0.0 = chaos, 1.0 = total peace')),
                ('config', models.JSONField(default=dict)),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world', to='simulation.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='EconomicTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField()),
                ('from_agent_id', models.PositiveIntegerField(blank=True, null=True)),
                ('to_agent_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='world.world')),
            ],
            options={
                'ordering': ['-tick'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zone_type', models.CharField(choices=[('urban', 'Urban'), ('rural', 'Rural'), ('wilderness', 'Wilderness'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=20)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=100.0)),
                ('height', models.FloatField(default=100.0)),
                ('resources', models.JSONField(default=dict, help_text='Resources available in the zone')),
                ('population_capacity', models.PositiveIntegerField(default=100)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='world.world')),
            ],
        ),
    ]
