# Generated by Django 5.1.15 on 2026-04-05 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_group_formed_at_tick'),
        ('simulation', '0004_simulation_report'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_type', models.CharField(default='democracy', max_length=30)),
                ('stability', models.FloatField(default=0.5, help_text='0.0 = collapsing, 1.0 = rock solid')),
                ('institutional_trust', models.FloatField(default=0.5)),
                ('repression_level', models.FloatField(default=0.1)),
                ('corruption', models.FloatField(default=0.2)),
                ('popular_legitimacy', models.FloatField(default=0.5)),
                ('military_loyalty', models.FloatField(default=0.5)),
                ('last_election_tick', models.PositiveIntegerField(default=0)),
                ('formed_at_tick', models.PositiveIntegerField(default=0)),
                ('head_of_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_governments', to='agents.agent')),
                ('ruling_faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruled_governments', to='agents.group')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='government', to='simulation.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government_type', models.CharField(max_length=30)),
                ('head_of_state_name', models.CharField(blank=True, max_length=255)),
                ('ruling_faction_name', models.CharField(blank=True, max_length=255)),
                ('from_tick', models.PositiveIntegerField()),
                ('to_tick', models.PositiveIntegerField(blank=True, null=True)),
                ('transition_cause', models.CharField(max_length=50)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_history', to='simulation.simulation')),
            ],
            options={
                'ordering': ['-from_tick'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('justice', 'Justice'), ('education', 'Education'), ('health', 'Health'), ('military', 'Military'), ('media', 'Media'), ('religion', 'Religion'), ('bureaucracy', 'Bureaucracy')], max_length=20)),
                ('health', models.FloatField(default=0.5, help_text='0.0 = failed, 1.0 = thriving')),
                ('independence', models.FloatField(default=0.5, help_text='0.0 = government controlled, 1.0 = fully independent')),
                ('funding', models.FloatField(default=0.5, help_text='0.0 = defunded, 1.0 = well funded')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='simulation.simulation')),
            ],
            options={
                'unique_together': {('simulation', 'institution_type')},
            },
        ),
    ]
