# Generated by Django 5.1.15 on 2026-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_zone_postgis_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='distance_scale',
            field=models.FloatField(default=133.0, help_text='Meters per grid unit. Converts abstract coordinates to real-world distances.'),
        ),
        migrations.AddField(
            model_name='world',
            name='tick_duration_hours',
            field=models.FloatField(default=24.0, help_text='Hours per simulation tick. Used to compute travel distances.'),
        ),
    ]
