# Generated by Django 5.1.15 on 2026-04-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0009_agent_birth_tick_agent_caretaker_agent_and_more'),
        ('simulation', '0005_simulation_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFertilityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avoid_conception_flag_tick', models.PositiveIntegerField(blank=True, null=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fertility_state', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_a_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('agent_b_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('formed_at_tick', models.PositiveIntegerField()),
                ('dissolved_at_tick', models.PositiveIntegerField(blank=True, null=True)),
                ('dissolution_reason', models.CharField(blank=True, choices=[('death', 'Death of a partner'), ('separate', 'Voluntary separation'), ('annulment', 'Annulment')], max_length=20)),
                ('couple_type', models.CharField(choices=[('monogamous', 'Monogamous'), ('arranged', 'Arranged')], default='monogamous', max_length=20)),
                ('agent_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couple_as_a', to='agents.agent')),
                ('agent_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couple_as_b', to='agents.agent')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples', to='simulation.simulation')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'dissolved_at_tick'], name='demography__simulat_136c13_idx'), models.Index(fields=['agent_a', 'dissolved_at_tick'], name='demography__agent_a_ddd879_idx'), models.Index(fields=['agent_b', 'dissolved_at_tick'], name='demography__agent_b_557390_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemographyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('birth', 'Birth'), ('death', 'Death'), ('pair_bond', 'Pair bond'), ('separate', 'Separate'), ('migration', 'Migration'), ('inheritance_transfer', 'Inheritance transfer'), ('mass_flight', 'Mass flight'), ('trapped_crisis', 'Trapped crisis'), ('demographic_initializer', 'Demographic initializer')], max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('primary_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demography_events_primary', to='agents.agent')),
                ('secondary_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demography_events_secondary', to='agents.agent')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demography_events', to='simulation.simulation')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'tick'], name='demography__simulat_c21689_idx'), models.Index(fields=['simulation', 'event_type', 'tick'], name='demography__simulat_fcd720_idx')],
            },
        ),
        migrations.CreateModel(
            name='PopulationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField()),
                ('total_alive', models.PositiveIntegerField(default=0)),
                ('age_pyramid', models.JSONField(default=list, help_text='List of [age_bucket_low, age_bucket_high, count_male, count_female]')),
                ('sex_ratio', models.FloatField(default=1.0)),
                ('avg_age', models.FloatField(default=0.0)),
                ('crude_birth_rate', models.FloatField(default=0.0)),
                ('crude_death_rate', models.FloatField(default=0.0)),
                ('tfr_instant', models.FloatField(default=0.0)),
                ('net_migration_by_zone', models.JSONField(default=dict)),
                ('couples_active', models.PositiveIntegerField(default=0)),
                ('avg_household_size', models.FloatField(default=0.0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_snapshots', to='simulation.simulation')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'tick'], name='demography__simulat_dccb44_idx')],
                'unique_together': {('simulation', 'tick')},
            },
        ),
    ]
