# Generated by Django 5.1.15 on 2026-04-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agent_birth_tick_alter_agent_parent_agent'),
        ('demography', '0002_birth_tick_backfill'),
        ('simulation', '0005_simulation_snapshot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='couple',
            constraint=models.CheckConstraint(condition=models.Q(('agent_a__isnull', True), ('agent_b__isnull', True), ('agent_a__lt', models.F('agent_b')), _connector='OR'), name='couple_canonical_ordering'),
        ),
    ]
