# Generated by Django 5.1.15 on 2026-04-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agent_birth_tick_alter_agent_parent_agent'),
        ('demography', '0003_couple_couple_canonical_ordering'),
        ('simulation', '0005_simulation_snapshot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='couple',
            constraint=models.UniqueConstraint(condition=models.Q(('dissolved_at_tick__isnull', True)), fields=('agent_a', 'agent_b'), name='unique_active_couple'),
        ),
    ]
