# Generated by Django 5.1.15 on 2026-08-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demography", "0004_couple_unique_active_couple"),
    ]

    operations = [
        migrations.AlterField(
            model_name="populationsnapshot",
            name="sex_ratio",
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
