# Generated by Django 5.1.15 on 2026-04-06 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0004_simulation_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField()),
                ('population_alive', models.PositiveIntegerField(default=0)),
                ('population_dead', models.PositiveIntegerField(default=0)),
                ('avg_wealth', models.FloatField(default=0.0)),
                ('gini_coefficient', models.FloatField(default=0.0)),
                ('avg_mood', models.FloatField(default=0.0)),
                ('faction_count', models.PositiveIntegerField(default=0)),
                ('government_type', models.CharField(blank=True, max_length=30)),
                ('government_stability', models.FloatField(default=0.0)),
                ('institutional_trust', models.FloatField(default=0.0)),
                ('repression_level', models.FloatField(default=0.0)),
                ('corruption', models.FloatField(default=0.0)),
                ('popular_legitimacy', models.FloatField(default=0.0)),
                ('military_loyalty', models.FloatField(default=0.0)),
                ('class_elite_pct', models.FloatField(default=0.0)),
                ('class_wealthy_pct', models.FloatField(default=0.0)),
                ('class_middle_pct', models.FloatField(default=0.0)),
                ('class_working_pct', models.FloatField(default=0.0)),
                ('class_poor_pct', models.FloatField(default=0.0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='simulation.simulation')),
            ],
            options={
                'ordering': ['tick'],
                'unique_together': {('simulation', 'tick')},
            },
        ),
    ]
