# Generated by Django 5.1.15 on 2026-04-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulation', '0005_simulation_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=5)),
                ('is_primary', models.BooleanField(default=True)),
                ('total_supply', models.FloatField(help_text="M in Fisher's MV=PQ: total money in circulation")),
                ('cached_velocity', models.FloatField(default=1.0, help_text="V in Fisher's MV=PQ: recomputed each tick from transaction volume, NOT a stored constant")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='simulation.simulation')),
            ],
            options={
                'unique_together': {('simulation', 'code')},
            },
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_essential', models.BooleanField(default=False, help_text='Essential goods cause crisis when scarce')),
                ('base_price', models.FloatField(help_text='Initial price in the primary currency')),
                ('price_elasticity', models.FloatField(help_text='|Price elasticity of demand|: 0=inelastic, 1=unit, >1=elastic')),
                ('config', models.JSONField(default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_categories', to='simulation.simulation')),
            ],
            options={
                'unique_together': {('simulation', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_factors', to='simulation.simulation')),
            ],
            options={
                'unique_together': {('simulation', 'code')},
            },
        ),
    ]
