# Generated by Django 5.1.15 on 2026-04-12 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agent_postgis_location'),
        ('economy', '0001_initial'),
        ('simulation', '0005_simulation_snapshot'),
        ('world', '0005_government_treasury'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holdings', models.JSONField(default=dict, help_text='{good_code: quantity}')),
                ('cash', models.JSONField(default=dict, help_text='{currency_code: amount}')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='TaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_tax_rate', models.FloatField(help_text='Flat income tax rate (0.0-1.0). Applied to wages + rent.')),
                ('config', models.JSONField(default=dict, help_text='Extensible for spec 2: progressive rates, property tax, tariffs')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_policy', to='simulation.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneEconomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_resources', models.JSONField(default=dict, help_text='{factor_code: abundance_float}')),
                ('production_config', models.JSONField(default=dict, help_text='{good_code: {factors: {factor_code: exponent}, scale: A, sigma: sigma_CES}}')),
                ('market_prices', models.JSONField(default=dict, help_text='{good_code: current_price} -- snapshot cache')),
                ('market_supply', models.JSONField(default=dict)),
                ('market_demand', models.JSONField(default=dict)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economy', to='world.zone')),
            ],
        ),
        migrations.CreateModel(
            name='EconomicLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField()),
                ('quantity', models.FloatField(default=0.0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('total_amount', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('production', 'Production'), ('trade', 'Trade'), ('tax', 'Tax'), ('rent', 'Rent'), ('wage', 'Wage')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.currency')),
                ('from_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to='agents.agent')),
                ('good_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='economy.goodcategory')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economic_ledger', to='simulation.simulation')),
                ('to_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to='agents.agent')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'tick'], name='economy_eco_simulat_6304b5_idx'), models.Index(fields=['from_agent'], name='economy_eco_from_ag_0e2f1b_idx'), models.Index(fields=['to_agent'], name='economy_eco_to_agen_c4b2d6_idx'), models.Index(fields=['simulation', 'transaction_type', 'tick'], name='economy_eco_simulat_56fd31_idx')],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('agent', 'Agent'), ('government', 'Government'), ('commons', 'Commons (unowned)')], max_length=20)),
                ('property_type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField(help_text='Estimated value in primary currency')),
                ('production_bonus', models.JSONField(default=dict, help_text='{good_code: multiplier} -- how much this property boosts production of each good in its zone')),
                ('config', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to='agents.agent')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='simulation.simulation')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='world.zone')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'owner_type'], name='economy_pro_simulat_9ae23b_idx'), models.Index(fields=['simulation', 'zone'], name='economy_pro_simulat_730665_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_code', models.CharField(max_length=30)),
                ('tick', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('supply', models.FloatField()),
                ('demand', models.FloatField()),
                ('zone_economy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='economy.zoneeconomy')),
            ],
            options={
                'indexes': [models.Index(fields=['zone_economy', 'good_code', 'tick'], name='economy_pri_zone_ec_931ff2_idx')],
                'unique_together': {('zone_economy', 'good_code', 'tick')},
            },
        ),
    ]
