# Generated by Django 5.1.15 on 2026-04-13 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agent_postgis_location'),
        ('economy', '0003_template'),
        ('simulation', '0005_simulation_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deposits', models.FloatField(default=0.0, help_text='Sum of all agent deposits in the banking system')),
                ('total_loans_outstanding', models.FloatField(default=0.0, help_text='Sum of all active loan balances')),
                ('reserve_ratio', models.FloatField(help_text='Fraction of deposits held as reserves (0.0-1.0)')),
                ('base_interest_rate', models.FloatField(help_text='Base lending rate before risk adjustments')),
                ('is_solvent', models.BooleanField(default=True, help_text='False triggers credit freeze (Diamond & Dybvig 1983)')),
                ('confidence_index', models.FloatField(default=1.0, help_text='0.0 = bank run imminent, 1.0 = full confidence')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking_state', to='simulation.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.FloatField(help_text='Price set by the seller, may differ from fundamental value')),
                ('fundamental_value', models.FloatField(help_text='Gordon (1959) intrinsic value: D / (r - g)')),
                ('listed_at_tick', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('sold', 'Sold'), ('withdrawn', 'Withdrawn')], default='listed', max_length=15)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='economy.property')),
            ],
        ),
        migrations.CreateModel(
            name='AgentExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_code', models.CharField(max_length=30)),
                ('expected_price', models.FloatField(help_text="Agent's expected price for next tick (Nerlove 1958)")),
                ('trend_direction', models.CharField(choices=[('rising', 'Rising'), ('falling', 'Falling'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('confidence', models.FloatField(default=0.5, help_text='0.0 = no confidence, 1.0 = certain. Increases when expectations match reality.')),
                ('lambda_rate', models.FloatField(help_text='Adaptation speed [0.05, 0.95], modulated by Big Five personality (Costa & McCrae 1992)')),
                ('updated_at_tick', models.PositiveIntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectations', to='agents.agent')),
            ],
            options={
                'unique_together': {('agent', 'good_code')},
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_type', models.CharField(choices=[('agent', 'Agent'), ('banking', 'Banking system')], max_length=10)),
                ('principal', models.FloatField(help_text='Original loan amount in primary currency')),
                ('interest_rate', models.FloatField(help_text='Per-tick interest rate (not annualized)')),
                ('remaining_balance', models.FloatField(help_text='Outstanding balance including accrued interest')),
                ('issued_at_tick', models.PositiveIntegerField()),
                ('due_at_tick', models.PositiveIntegerField(blank=True, help_text='Null for open-ended loans', null=True)),
                ('times_rolled_over', models.PositiveIntegerField(default=0, help_text='Rollover count; high values signal Minsky fragility')),
                ('status', models.CharField(choices=[('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('rolled_over', 'Rolled over')], default='active', max_length=15)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_taken', to='agents.agent')),
                ('collateral', models.ForeignKey(blank=True, help_text='Property pledged as collateral (Stiglitz & Weiss 1981)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collateralized_loans', to='economy.property')),
                ('lender', models.ForeignKey(blank=True, help_text="Null when lender_type is 'banking' (system-level credit)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_given', to='agents.agent')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='simulation.simulation')),
            ],
            options={
                'indexes': [models.Index(fields=['simulation', 'status'], name='economy_loa_simulat_b44782_idx'), models.Index(fields=['borrower', 'status'], name='economy_loa_borrowe_b8277e_idx'), models.Index(fields=['lender', 'status'], name='economy_loa_lender__b344bf_idx')],
            },
        ),
    ]
