# Generated by Django 5.1.15 on 2026-04-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_behavioral_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicledger',
            name='transaction_type',
            field=models.CharField(choices=[('production', 'Production'), ('trade', 'Trade'), ('tax', 'Tax'), ('rent', 'Rent'), ('wage', 'Wage'), ('property_sale', 'Property Sale'), ('loan_issued', 'Loan Issued'), ('loan_interest', 'Loan Interest'), ('expropriation', 'Expropriation')], max_length=20),
        ),
    ]
