# Generated by Django 5.1.15 on 2026-07-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0005_alter_economicledger_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="economicledger",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("production", "Production"),
                    ("trade", "Trade"),
                    ("tax", "Tax"),
                    ("rent", "Rent"),
                    ("wage", "Wage"),
                    ("profit", "Profit"),
                    ("property_sale", "Property Sale"),
                    ("loan_issued", "Loan Issued"),
                    ("loan_interest", "Loan Interest"),
                    ("expropriation", "Expropriation"),
                ],
                max_length=20,
            ),
        ),
    ]
