# Generated by Django 5.1.15 on 2026-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0007_alter_economicledger_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("repaid", "Repaid"),
                    ("defaulted", "Defaulted"),
                    ("default_settled", "Default settled"),
                    ("rolled_over", "Rolled over"),
                ],
                default="active",
                max_length=15,
            ),
        ),
    ]
