# Generated by Django 5.1.15 on 2026-07-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0008_alter_loan_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="cached_velocity",
            field=models.FloatField(
                default=1.0,
                help_text="Measured turnover velocity (transaction volume / M), recomputed each tick; reported metric only -- the Fisher diagnostic uses the engine-computed income velocity",
            ),
        ),
    ]
