# Generated by Django 5.1.15 on 2026-07-16 08:10

from django.db import migrations, models


def settle_processed_defaults(apps, schema_editor):
    """Backfill the terminal state for pre-0008 processed defaults.

    R6-MIG-1 fix (Round 6 re-audit): migration 0008 introduced the
    terminal default_settled status but shipped no data migration, so
    every loan already sitting in status="defaulted" on an existing
    database would be re-processed once more on the first post-upgrade
    tick (collateral re-seized, banking write-off re-applied,
    reputation damage re-fired). Pre-0008 process_defaults always
    zeroed remaining_balance when it handled a default, so a defaulted
    loan with remaining_balance == 0 has already been processed and is
    moved to the terminal state. Defaulted loans with a nonzero
    balance (marked but never processed) are left for the normal
    pipeline.
    """
    Loan = apps.get_model("economy", "Loan")
    Loan.objects.filter(status="defaulted", remaining_balance=0.0).update(status="default_settled")


def unsettle_processed_defaults(apps, schema_editor):
    Loan = apps.get_model("economy", "Loan")
    Loan.objects.filter(status="default_settled").update(status="defaulted")


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0009_alter_currency_cached_velocity"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="cascade_origin",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True when the default was forced by the contagion cascade "
                    "(Allen and Gale 2000) rather than by servicing/maturity "
                    "failure. R6-CASC-1 fix: the loss of a cascade-defaulted "
                    "loan is threshold-evaluated in-tick by the BFS, so its "
                    "settlement records must not re-seed the next tick's "
                    "cascade (double evaluation of one loss event)."
                ),
            ),
        ),
        migrations.RunPython(settle_processed_defaults, unsettle_processed_defaults),
    ]
