# Generated by Django 5.1.15 on 2026-04-12 09:55

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agent_postgis_location'),
        ('knowledge', '0003_extraction_cache'),
        ('simulation', '0005_simulation_snapshot'),
        ('world', '0004_world_distance_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('building', 'Building'), ('ready', 'Ready'), ('error', 'Error'), ('stale', 'Stale')], default='building', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, related_name='graphs', to='knowledge.knowledgedocument')),
                ('extraction_cache', models.ForeignKey(help_text='Cache entry this graph was materialised from', on_delete=django.db.models.deletion.PROTECT, related_name='graphs', to='knowledge.extractioncache')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph', to='simulation.simulation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('group', 'Group'), ('institution', 'Institution'), ('place', 'Place'), ('event', 'Event'), ('concept', 'Concept'), ('resource', 'Resource'), ('technology', 'Technology'), ('law', 'Law'), ('artifact', 'Artifact')], max_length=20)),
                ('name', models.CharField(help_text='Display name as found in source', max_length=255)),
                ('canonical_name', models.CharField(db_index=True, help_text='Lowercased, deduplicated canonical form', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names encountered in source documents')),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Structured attributes extracted from text (dates, roles, etc.)')),
                ('source_type', models.CharField(choices=[('document', 'Extracted from document'), ('document_inferred', 'Inferred from document context')], max_length=30)),
                ('confidence', models.FloatField(help_text='Extraction confidence score, 0.0 to 1.0')),
                ('mention_count', models.PositiveIntegerField(default=1, help_text='Number of distinct mentions across chunks')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='knowledge.knowledgegraph')),
                ('linked_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_nodes', to='agents.agent')),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_nodes', to='simulation.event')),
                ('linked_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_nodes', to='agents.group')),
                ('linked_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_nodes', to='world.institution')),
                ('linked_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_nodes', to='world.zone')),
            ],
            options={
                'ordering': ['-confidence', 'canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeNodeCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_excerpt', models.TextField(help_text='Relevant text fragment from the chunk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_citations', to='knowledge.knowledgechunk')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='knowledge.knowledgenode')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('ally_of', 'Ally of'), ('rival_of', 'Rival of'), ('member_of', 'Member of'), ('leader_of', 'Leader of'), ('located_in', 'Located in'), ('born_in', 'Born in'), ('died_in', 'Died in'), ('participated_in', 'Participated in'), ('caused', 'Caused'), ('resulted_in', 'Resulted in'), ('preceded', 'Preceded'), ('succeeded', 'Succeeded'), ('influenced', 'Influenced'), ('opposed', 'Opposed'), ('traded_with', 'Traded with'), ('governed', 'Governed'), ('created', 'Created'), ('destroyed', 'Destroyed'), ('related_to', 'Related to'), ('unknown', 'Unknown')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('document', 'Extracted from document'), ('document_inferred', 'Inferred from document context')], max_length=30)),
                ('confidence', models.FloatField(help_text='Extraction confidence score, 0.0 to 1.0')),
                ('weight', models.FloatField(default=1.0, help_text='Edge weight for graph algorithms (higher = stronger relationship)')),
                ('temporal_start_iso', models.CharField(blank=True, help_text="Original temporal reference for start (e.g. 'summer 1789')", max_length=100)),
                ('temporal_start_year', models.IntegerField(blank=True, help_text='Parsed start year for range queries', null=True)),
                ('temporal_end_iso', models.CharField(blank=True, help_text='Original temporal reference for end', max_length=100)),
                ('temporal_end_year', models.IntegerField(blank=True, help_text='Parsed end year for range queries', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='knowledge.knowledgegraph')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='knowledge.knowledgenode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='knowledge.knowledgenode')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelationCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_excerpt', models.TextField(help_text='Relevant text fragment from the chunk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_citations', to='knowledge.knowledgechunk')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='knowledge.knowledgerelation')),
            ],
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['graph', 'entity_type'], name='knowledge_k_graph_i_eb33db_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='node_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgenode',
            unique_together={('graph', 'entity_type', 'canonical_name')},
        ),
        migrations.AlterUniqueTogether(
            name='knowledgenodecitation',
            unique_together={('node', 'chunk')},
        ),
        migrations.AddIndex(
            model_name='knowledgerelation',
            index=models.Index(fields=['graph', 'relation_type'], name='knowledge_k_graph_i_1b7c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelation',
            index=models.Index(fields=['source_node', 'target_node'], name='knowledge_k_source__63b4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelation',
            index=models.Index(fields=['temporal_start_year', 'temporal_end_year'], name='knowledge_k_tempora_c829c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgerelationcitation',
            unique_together={('relation', 'chunk')},
        ),
    ]
