# Generated by Django 5.1.15 on 2026-04-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_graph_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgegraph',
            name='materialized_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when materialization completed successfully', null=True),
        ),
    ]
