# Generated by Django 5.1.15 on 2026-04-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_materialized_at_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgenode',
            old_name='properties',
            new_name='attributes',
        ),
    ]
