# Generated by Django 5.1.15 on 2026-03-27 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.PositiveIntegerField()),
                ('input_context', models.TextField(help_text='Context sent to the LLM')),
                ('output_decision', models.TextField(help_text='Decision made by the LLM')),
                ('llm_model', models.CharField(max_length=100)),
                ('cost_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tick'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('objective', models.TextField(blank=True)),
                ('cohesion', models.FloatField(default=0.5, help_text='0.0 = fragmented, 1.0 = monolithic')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('emotional_weight', models.FloatField(default=0.5, help_text='0.0 = trivial, 1.0 = traumatic/ecstatic')),
                ('source_type', models.CharField(choices=[('direct', 'Direct experience'), ('hearsay', 'Hearsay'), ('public', 'Public source'), ('rumor', 'Rumor')], default='direct', max_length=20)),
                ('reliability', models.FloatField(default=1.0, help_text='0.0 = unreliable, 1.0 = certain')),
                ('tick_created', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, help_text='False = faded memory')),
            ],
            options={
                'ordering': ['-emotional_weight', '-tick_created'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('friendship', 'Friendship'), ('rivalry', 'Rivalry'), ('family', 'Family'), ('romantic', 'Romantic'), ('professional', 'Professional'), ('distrust', 'Distrust')], max_length=20)),
                ('strength', models.FloatField(default=0.5, help_text='0.0 = weak, 1.0 = very strong')),
                ('sentiment', models.FloatField(default=0.0, help_text='-1.0 = hatred, 1.0 = love')),
                ('since_tick', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(default=25)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary')], default='male', max_length=20)),
                ('sexual_orientation', models.CharField(choices=[('heterosexual', 'Heterosexual'), ('homosexual', 'Homosexual'), ('bisexual', 'Bisexual'), ('asexual', 'Asexual')], default='heterosexual', max_length=20)),
                ('role', models.CharField(blank=True, help_text='Role in society (blacksmith, priest, farmer...)', max_length=100)),
                ('personality', models.JSONField(default=dict, help_text='Full personality profile: Big Five (openness, conscientiousness, extraversion, agreeableness, neuroticism), character traits, temperament, ambitions, fears, values, beliefs, humor style, attachment style')),
                ('intelligence', models.FloatField(default=0.5, help_text='0.0 = very low, 0.5 = average, 1.0 = genius')),
                ('emotional_intelligence', models.FloatField(default=0.5, help_text='0.0 = oblivious, 1.0 = deeply empathetic')),
                ('creativity', models.FloatField(default=0.5, help_text='0.0 = conventional, 1.0 = highly creative')),
                ('cunning', models.FloatField(default=0.5, help_text='0.0 = naive, 1.0 = extremely shrewd')),
                ('strength', models.FloatField(default=0.5, help_text='0.0 = frail, 1.0 = extremely strong')),
                ('stamina', models.FloatField(default=0.5, help_text='0.0 = no endurance, 1.0 = tireless')),
                ('agility', models.FloatField(default=0.5, help_text='0.0 = clumsy, 1.0 = extremely agile')),
                ('health', models.FloatField(default=1.0, help_text='0.0 = dead, 1.0 = perfect health')),
                ('mental_health', models.FloatField(default=0.8, help_text='0.0 = severe disorder, 1.0 = thriving')),
                ('conditions', models.JSONField(default=list, help_text='List of active conditions: diseases, disabilities, addictions')),
                ('fertility', models.FloatField(default=0.8, help_text='0.0 = infertile, 1.0 = highly fertile')),
                ('wealth', models.FloatField(default=50.0)),
                ('mood', models.FloatField(default=0.5, help_text='0.0 = desperate, 1.0 = euphoric')),
                ('charisma', models.FloatField(default=0.5, help_text='0.0 = repulsive, 1.0 = magnetic')),
                ('education_level', models.FloatField(default=0.3, help_text='0.0 = illiterate, 1.0 = scholar')),
                ('social_class', models.CharField(default='working', help_text='elite, wealthy, middle, working, poor, enslaved', max_length=30)),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('is_alive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_agent', models.ForeignKey(blank=True, help_text='Biological parent (for lineage tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='agents.agent')),
            ],
        ),
    ]
