# Generated by Django 5.1.15 on 2026-04-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['agent', 'is_active', '-tick_created'], name='memory_dedup_idx'),
        ),
    ]
