# Generated by Django 5.1.15 on 2026-04-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_group_formed_at_tick'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FloatField(default=0.0, help_text='-1.0 = terrible, 0.0 = neutral, 1.0 = excellent (direct experience)')),
                ('reputation', models.FloatField(default=0.0, help_text='-1.0 = terrible, 0.0 = neutral, 1.0 = excellent (social evaluation)')),
                ('last_updated_tick', models.PositiveIntegerField(default=0)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_assessments', to='agents.agent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_scores', to='agents.agent')),
            ],
            options={
                'indexes': [models.Index(fields=['holder', 'target'], name='reputation_lookup_idx')],
                'unique_together': {('holder', 'target')},
            },
        ),
    ]
