# Generated by Django 5.1.15 on 2026-04-06 14:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_reputation_score'),
        ('world', '0003_zone_postgis_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='position_y',
        ),
        migrations.AddField(
            model_name='agent',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Current geographic position (WGS84)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='agent',
            name='zone',
            field=models.ForeignKey(blank=True, help_text='Current zone (denormalized for performance)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_in_zone', to='world.zone'),
        ),
    ]
