# Generated by Django 5.1.15 on 2026-04-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_decisionlog_agents_deci_simulat_cfe24f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='birth_tick',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Canonical age source; age = (current_tick - birth_tick) / ticks_per_year', null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='caretaker_agent',
            field=models.ForeignKey(blank=True, help_text='Active caretaker for a minor when parents are unavailable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='death_cause',
            field=models.CharField(blank=True, choices=[('natural_senescence', 'Natural senescence'), ('early_life_mortality', 'Early-life mortality'), ('external_cause', 'External cause'), ('childbirth', 'Childbirth'), ('starvation', 'Starvation'), ('expropriation', 'Expropriation'), ('executed', 'Executed'), ('unknown', 'Unknown')], max_length=30),
        ),
        migrations.AddField(
            model_name='agent',
            name='death_tick',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='other_parent_agent',
            field=models.ForeignKey(blank=True, help_text='Second biological parent (father by Epocha convention)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_parent_children', to='agents.agent'),
        ),
    ]
